# Generated by Django 3.1.3 on 2020-11-05 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0004_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.market')),
            ],
        ),
    ]
