# Generated by Django 3.1.3 on 2020-11-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0003_bucket_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
