# Generated by Django 3.1.3 on 2020-11-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0004_auto_20201106_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
