# Generated by Django 3.1.3 on 2020-11-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_market'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Item',
        ),
        migrations.RemoveField(
            model_name='market',
            name='stock',
        ),
        migrations.AddField(
            model_name='market',
            name='item',
            field=models.ManyToManyField(to='stock.Item'),
        ),
    ]
