# Generated by Django 3.1.3 on 2020-11-06 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20201106_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.market'),
            preserve_default=False,
        ),
    ]
