# Generated by Django 3.1.3 on 2020-11-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20201106_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date',
        ),
    ]
