# Generated by Django 3.1.3 on 2020-11-06 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='date',
            new_name='date_market',
        ),
        migrations.AddField(
            model_name='market',
            name='deadline_cart',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
