# Generated by Django 3.1.3 on 2020-11-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.IntegerField(choices=[(1, 'Pièce'), (2, 'kilo'), (3, 'kilo')], default=1),
        ),
    ]
